order.php
Integration of Shapeshift.io for accepts altcoins in Woocommerce
=> Shapeshift.iot Integration

order.php
Also modified the styles for a better mobile experience
=> Modifying checkout to match issue 19

order.php
- Added left border back to pay with altcoin
- Reduced width of order pane
- Reduced font size of QR subtitle and shapeshift subtitle
=> Fixes to order page

blockonomics-woocommerce.php, php/Blockonomics.php
=> Intelligent error display on plugin

blockonomics-woocommerce.php
Fix for issue #78, ignore schema when comparing callback urls
=> Fix for issue #78, ignore schema when comparing callback urls

blockonomics-woocommerce.php, order.php, php/Blockonomics.php, php/Flyp.php
Fix for issue  [#69](https://github.com/blockonomics/woocommerce-plugin/issues/69), [use wp_remote for requests](https://github.com/blockonomics/woocommerce-plugin/commit/ce1a65927ace89cd4b2d227adc57be63b1b99a8f)
=> Fix for issue #69, use wp_remote for requests

blockonomics-woocommerce.php
=> fixes #94, Prompting users to review plugin on three admin pages

blockonomics-woocommerce.php
Fix issue #97, Replace order->id with order->get_id()
=> Fix issue #97, Update get_post_meta order->id

blockonomics-woocommerce.php, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php
One click setup changes for review
=> One click setup

js/app.js
Fixes for issues #103
* Added code comments
* Moved altcoin create to altcoin controller
* Added cancel_check_order
* Removed duplicate code, added function process_alt_response
* Simplified success functions
Email still dependant on send_email
=> Altcoin refunds pending issues #103

blockonomics-woocommerce.php, css/order.css, js/app.js, templates/track.php
Added spinner
Fix low/high error
=> Altcoin refunds

js/app.js
Added referral code to create order #126
=> #126 Add referral code to create order

php/WC_Gateway_Blockonomics.php
Added rounding to satoshi calculation, #121
=> Issue #121, Add rounding to satoshi calculation

blockonomics-woocommerce.php
Add defer param to enqueue scripts #71
=> Wp enqueue scripts async

php/Blockonomics.php
Issue #124, increase wp_remote_post timeout to 8s for new address.
=> Wp remote post timeout

blockonomics-woocommerce.php, php/WC_Gateway_Blockonomics.php
Enqueue stylesheets on correct pages, #125
=> Enqueue script fix - Issue #125

templates/order.php, templates/track.php
Fix for the Divi theme and child themes.
Does not interfere with other themes.
Commit 9c64b89 contains fix for any theme in array but does not include header, footer or any site branding. (deprecated in this pull request)
=> Divi simple fix

blockonomics-woocommerce.php, css/order.css, js/app.js, templates/order.php
Solutions for lite mode automations, #137
- 8e1b4b8 If the lite mode setting has not been set before then check if a known problem theme is being used
- a3ff8e0 Detects if app.js is executing on order.php correctly
=> Lite Mode Automation #137

js/app.js
Fixes the link in the altcoin refund email
=> Fix altcoin refund link

blockonomics-woocommerce.php, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php
Fixes for Debug Mode Warnings #140
=> Debug warnings

js/app.js, templates/order.php
Move create order to checkout controller #143
=> Fix refreshing altcoin order issue #143

js/app.js, templates/track.php
Update handling of expired flyp orders to add refund address #144
=> Flypme handle expired #144

js/app.js
=> Flyp Improvements

css/order.css, templates/order.php
Restyle some font size, and added link to how to pay.
=> How to Pay Link added + Restyling

.gitignore, js/app.js, php/WC_Gateway_Blockonomics.php, templates/order.php
Refresh keeps using same order id, same address, only resetting timer (clock). Question, should I reset the timestamp as well?
=> Added refresh on expiry

js/app.js
Callbacks not being delivered before websocket redirect
$interval replaced with $timeout
=> Replace interval with timeout

blockonomics-woocommerce.php
Fix for plugin conflict, issue #168
=> Plugin conflict

README.md, blockonomics-woocommerce.php
Set Tested upto Tag to support latest wordpress
Set WC Tested upto Tag to support latest woocommerce
=> Tested up to

README.md, php/Blockonomics.php
Replace freshdesk URLs with http://help.blockonomics.co
=> Update freshdesk URLs

php/WC_Gateway_Blockonomics.php
Handle error in case order not found by address, #172
=> Handle order not found, #172

templates/blockonomics_checkout.php, templates/blockonomics_crypto_options.php
Fix issue #194 
Reinstates the class that that only shows the message after 3 seconds
=> Delay displaying lite-mode error

js/app.js, php/Blockonomics.php
=> Fix payment expires early

templates/blockonomics_checkout.php, templates/blockonomics_crypto_options.php
I am not sure why this include is there but it is giving a warning https://prnt.sc/u3maga
Even after removing include everything is working.
Please review
=> Fixes include warning

css/order.css, templates/blockonomics_crypto_options.php
Remove unused css styles
Uses block prefix
=> Remove unused css styles

php/Blockonomics.php
Fixes issues with test setup introduced during bch integration
=> Fix test setup temp wallet

blockonomics-woocommerce.php
Fix for lite mode issues when upgrading plugin versions.
=> Add blockonomics version to enqueue scripts

README.md
Remove Altcoins
Add Bitcoin Cash
=> Update readme to include bch

blockonomics-woocommerce.php, php/Blockonomics.php
Fixes issue #209 
Uses the new post meta titles to display the transaction info in the woocommerce order and email.
=> Fix issue #209

blockonomics-woocommerce.php
Fix for issue #213. 
Moved location Blockonomics.php is included.
=> Fix issue #213

php/Blockonomics.php
Fix for issue where some orders not changing status to processing
Fetch all the blockonomics orders on callback
=> Fix orders not changing status to processing

blockonomics-woocommerce.php, js/app.js, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php, templates/blockonomics_nojs_checkout.php
- Fixes issue #222 (atomic updates)
- Includes basic changes to move blockonomics_orders from wp options array to its own database table
=> Orders to db table

js/app.js, php/Blockonomics.php, templates/blockonomics_checkout.php
Showing gap limit error in checkout if present
=> Showing error message from server for gap limit issues, fixes #229

blockonomics-woocommerce.php, templates/blockonomics_crypto_options.php, templates/blockonomics_nojs_checkout.php
Secure filter_by attribute using esc_attr(), Issue #241
Tested the attribute is correctly escaped:
=> Fix escaping filter_by request

templates/blockonomics_nojs_checkout.php
It's a minor change, but it fixes Issue #255.
=> change cursor to text

css/order.css, templates/blockonomics_crypto_options.php
Related to Issue #252
This PR also includes the code that makes it possible to click/tap on the edge of the buttons too.
I've worked on getting it to look similar with different themes and on different devices. 
| _________________________________________|___________________________________________|_________________________________________|
| :---:         |     :---:      |          :---: |
|  Theme 1| Theme 2 | Theme 3|
This can be seen as a draft, feel welcome to come with suggestions for potential improvments.
=> Responsive crypto select buttons

blockonomics-woocommerce.php, js/app.js, php/Blockonomics.php, templates/blockonomics_nojs_checkout.php
Related to Issue #251.
The code has seen small changes, but it should be enough to implement the proposed changes. Every time a user refreshes the page, an API call will be sent to check and update the price, and the timer will be reset.
=> Reset checkout timer at refresh

blockonomics-woocommerce.php, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php, templates/blockonomics_crypto_options.php, templates/blockonomics_nojs_checkout.php
Fixes _Errors_ from security report
=> Security report fixes

php/Blockonomics.php
=> (fix) Callbacks exit without error for Non Existing Orders

js/app.js, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php, templates/blockonomics_nojs_checkout.php
Fixes #237 
Encrypts Order ID for various endpoints to prevent leakage of order info by incrementing IDs
=> (update) Encrypt Order IDs in checkout

php/Blockonomics.php
=> (fix) Error Template should not load JS

blockonomics-woocommerce.php
Fixes Cross Site Scripting (XSS) vulnerability. Escapes the filter_by attribute using wordrpess [esc_attr](https://developer.wordpress.org/reference/functions/esc_attr/) function.
=> Prevent XSS using esc_attr

css/order.css, js/checkout.js
- Refresh time remaining timing delay fix
- Use 300ms for completing animations
=> Refresh animation timing improvements

php/Blockonomics.php
=> (fix) order status >= 0 does not auto redirect

css/order.css, templates/blockonomics_nojs_checkout.php
References #283 
Closes #305 
Continuation for #298 
- Upgrades No JS Checkout to Modular
=> Phase 2: Upgrade No JS Checkout to Modular #298

js/checkout.js
1) Used prettier to solve all the missing semicolons in the code.
2) Remove the const data variable.
3)Replaced the line value: data by value: this. data.payment_uri.
Fixes: #292  
CAUSE:
(Reason for the bug{js syntax error} is missing semicolon )
=> Removing Unused Variable, and Fixing Missing Semicolon and used Prettier to make it readable (#292)

blockonomics-woocommerce.php, php/Blockonomics.php
With refernce to #325 #310 
Before disabling partial payment
After disabling partial payment
=> Disabled the partial payement

blockonomics-woocommerce.php, php/Blockonomics.php
The coupon code logic  was removed and added paid as well as the remaining amount for #310
Order completion
Order completion email
=> Remove coupon order

blockonomics-woocommerce.php, css/order.css, php/Blockonomics.php, templates/blockonomics_checkout.php
Image of the invoice with the link to the Blockonomics  checkout page:
Image of the checkout page:
=> Link to the Blockonomics checkout page form the invoice form

blockonomics-woocommerce.php, php/Blockonomics.php
Removed the note for partial payment invoice mail.
=> removed the note for coupon

blockonomics-woocommerce.php, php/Blockonomics.php
Reverts blockonomics/woocommerce-plugin#326
=> Enable partial payment

php/Blockonomics.php
Underpayment (Partial Payment Enabled) | Underpayment (Partial Payments Disabled) | Full Payment
---- | --- | --------
=> Display the order note

blockonomics-woocommerce.php, css/order.css, js/checkout.js, js/vendors/copytoclipboard.js, templates/blockonomics_checkout.php
=> Blockonomics checkout page copy to clipboard

css/order.css, js/checkout.js, templates/blockonomics_checkout.php
Made changes in the Blockonomics checkout template preview 
Web View  | Mobile view
---- | ---
=> Change template design for checkout blockonomics

blockonomics-woocommerce.php, php/Blockonomics.php, php/WC_Gateway_Blockonomics.php, templates/blockonomics_checkout.php, templates/blockonomics_crypto_options.php
https://github.com/blockonomics/woocommerce-plugin/assets/91294460/763042c9-b125-4ba6-8350-30236d095e97
**Page Creation ->Creating Shortcode -> Page Redirect**
=> WC payment page change 

php/Blockonomics.php
Add the placeholder for the prepare function #344
=> Fixed the warning by adding placeholder to wpdb::prepare()

php/Blockonomics.php
=> Updating payment method title based on the currency used in the order

blockonomics-woocommerce.php
This PR fixes the issue where when upgraded, on race condition the payment page creation is failed.
=> Fixes the bug where payment page is failed to be created

README.md, blockonomics-woocommerce.php, css/blockonomics_options.css, php/Blockonomics.php
Removes the temp wallet support
=> Remove temp wallet support
