blockonomics-woocommerce.php

Fix for issue [#81](https://github.com/blockonomics/woocommerce-plugin/issues/81), check Woocommerce currency before fetching the price

Fix for issue #81, check currency before get price

---

php/WC_Gateway_Blockonomics.php

Fix order_key for previous woocommerce versions < 3, issue #161

Fix order_key for all woocommerce versions, issue #161

---

js/app.js
php/Blockonomics.php
templates/blockonomics_checkout.php

- order txid was not set before called record_payment method resulting in error. See screenshot
- simplified callback value compare logic
- In client, redirecting to order confirmation if status received indicates a successful transaction. Sometimes websocket may not work due to network disconnection or other issues. So UI wise it is preferable that refershing the page results in same behviour 
- Removed timestamp from websocket call to fix issues mentioned in https://github.com/blockonomics/woocommerce-plugin/pull/201

Fixed callback Issues

---

php/Blockonomics.php

Always fetches latest orders before updating an order, to ensure blockonomics_orders is up to date.

Fix issue #222, atomic update options

---

blockonomics-woocommerce.php

This PR is created to fix [this error](https://wordpress.org/support/topic/showing-sql-error-from-query-monitor/#post-14285132). I was able to recreate the error and has done some small changes in order to fix it.
There are mainly two things that have changed. The register_activation_hook() has been introduced. It is true that this is not called during an update. However, it seems to be necessary during plugin initiation. 
$sql _CREATE TABLE IF NOT EXISTS_ has been changed to _CREATE TABLE_. This is the way it is structured in the [WordPress documentation](https://codex.wordpress.org/Creating_Tables_with_Plugins). It seems to be the case that dbDelta() does not require _IF NOT EXISTS_, but will instead discern this itself.
As part of testing I've deleted, installed, upgraded the database, …

Fixing database error

---

blockonomics-woocommerce.php

Fix for the issue #241 
Correctly sanitizes the request data in the _filter_by_ input field using the WordPress [sanitize_text_field()](https://developer.wordpress.org/reference/functions/sanitize_text_field/) function.

Fix for issue #241, sanitize the filter_by request

---

php/Blockonomics.php

This is connected to issue #233 (Simplify callback checking in TestSetup). 
It follows the logic:
- First check if WP callback is exact match of an existing callback. Then do nothing
- Else replace callback with exact domain name match
- Else give error
This still need to be improved to work when merchant has set up multiple shops.

Simplify callback logic

---

js/app.js
php/Blockonomics.php
templates/blockonomics_checkout.php

Fixes issues with concurrent orders using the same bitcoin address.
- Saves the order to the blockonomics_orders table before updating the post metadata using record_address(). This ensures duplicates are checked before saving the address to the post
- Displays the _Temporary address error_ if SQL error on insert_order(), caused by the duplicate entry.
The fix can be tested using the following steps:
1. Create two new orders on WooCommerce. eg. Orders 1476 and 1477
2. Delete the two new orders from the blockonomics_orders table
3. Run the following curl command after replacing the two order_ids and your WordPress URL, in order to call get_order for both orders at the same time `seq 1476 1477 | xargs -I + -P2 curl 'http://localhost/wordpress/index.php/wc-api/WC_Gateway_Blockonomics?crypto=b …

Fix duplicate orders

---

blockonomics-woocommerce.php

Checks the database column exists before dropping the column using [maybe_drop_column](https://developer.wordpress.org/reference/functions/maybe_drop_column/).
Fix for error:
```
WordPress database error Can't DROP COLUMN `time_remaining`; check that it exists for query ALTER TABLE
wp_blockonomics_orders DROP COLUMN time_remaining, DROP COLUMN timestamp; made by require_once('wp-load.php'),
require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action,
WP_Hook->apply_filters, blockonomics_update_db_check
```

Quick fix for dropping columns if not exists

---

css/order.css

Closes https://github.com/blockonomics/woocommerce-plugin/issues/289 by uncommenting the `padding-top: 10vh;` i.e. reverting https://github.com/blockonomics/woocommerce-plugin/commit/1e49a3fad0c5fc14c38ad41707212c8ce347bf39

Post release fix for v3.5.6

---

blockonomics-woocommerce.php
php/Blockonomics.php

This PR addresses @shivaenigma's review comments on [underpayment PR](https://github.com/blockonomics/woocommerce-plugin/pull/310). 
Changes done are as follows:
- Removed db check for version 1.1 in _blockonomics_run_db_updates_ function
- Removed trivial comments
- Removed error thrown if _insert_order_ fails
- Updated underpayment message shown on order details page
Note: I have opened an [issue](https://github.com/blockonomics/woocommerce-plugin/issues/316) regarding underpayment logic being called from _calculate_order_params_
---
Order details screenshots:

Pre 3.5.9 release refactor

---

blockonomics-woocommerce.php
php/Blockonomics.php

Based on feedback after release of version 3.6, this PR gives merchants an option to disable/enable the partial payments flow using coupons. By default, partial payments are enabled.
---
**Screenshots**:
Advance settings
**Behavior if partial payments are disabled**: similar as was in prior to v3.6 i.e. status is set to Failed and Order note is added
Checkout when partial payments are disabled and order has been underpaid:
Order note changed to show paid fiat amount in case of underpayment when partial payments are off:
---
Use cases tested:
1. Fresh Install ✔
2. Upgrade from v3.6 ✔
4. No JS mode ✔
5. Lite Mode ✔
6. No JS + Lite Mode ✔

Add partial payments checkbox in settings

---

blockonomics-woocommerce.php

This fixes issue #314 
After changes : We can have multiple addresses & transaction ids but when this happens, they are now searchable from Filter on the Order History page (image attached).
Order 20 (multiple txid and address)

 Filter Issue fixed for multiple txids and address

---

blockonomics-woocommerce.php

Adding a feature to display links to the transaction id in the invoice.
This PR fixes the issue https://github.com/blockonomics/woocommerce-plugin/issues/319
Single transaction id
Multiple transaction id

Add new features:Display links to the transaction id in the invoice

---

blockonomics-woocommerce.php
php/Blockonomics.php

Recently, we released WordPress 3.6.5 and encountered a bug where the shortcode is parsed or executed multiple times. This can occur for various reasons, such as the SEO plugin parsing the shortcode multiple times.
This fix ensures that the shortcode runs only once by making certain all files are included just a single time. The QR code for 'nojs' is executed only when 'no-js' is activated

Resolves the bug  caused due to shortcode executing multiple times 

---

blockonomics-woocommerce.php

This is to align with the new change where shortcodes are run multiple times 
So we do not want to run the shortcode if it is executed in the head section  to support all in SEO and Elementor executions

Payment shortcode to be  not run on head

---

blockonomics-woocommerce.php
php/Blockonomics.php

- With our new change for payment page as shortcode, additional scripts which incldues `blockonomics_data` is not added for block based themes like Twentytwentythree.
All block based themes cannot load the checkout page as it shows a Display Error and has a JS error in the browser console.
To fix, instead of using `wp_add_inline_script` to add the script we need to use `wp_footer` action by adding the additional script at the bottom of the page.

Fixing additional script bug on block theme

---

blockonomics-woocommerce.php

Previously we used `clear_url` filter hook to added the defer attribute to the script tag. Which recently has been deprecated and is generating a invalid url for scripts. It looks something like this
```html
<script src="js/checkout.js?ver=3.6.7' defer='defer'"></script>
```
Now changed this by passing a stratergy `defer` to the `wp_register_script()`  and this creates the url correctly as below
```html
<script src="js/checkout.js?ver=3.6.9" defer="defer" data-wp-strategy="defer"></script>
```

Fixed JS script url and added defer attribute

---

php/Blockonomics.php

The proper value was not displayed at the payment details level
Solution  for the issue #361

bitcoin currency decimal issue

---

blockonomics-woocommerce.php

After the HPOS upgrade, woocommerce changed the way orders are stored.
So this PR check if HPOS is enabled and uses different logic to filter order by addresses or txids.

Fixed order filter caused by HPOS

---

blockonomics-woocommerce.php

This PR removes unwanted `require` to fix the Warnings which happens when running any WP–CLI command.
Fixes - https://wordpress.org/support/topic/warning-constant-db_name-already-defined-in-wp-config-php

Remove unwanted import to fix Warning: Constant DB_NAME already defined

---

.github/workflows/main.yml
.gitignore
README.md
composer.json
composer.lock
tests/BlockonomicsTest.php

This is phase 1 of testing for blockonomics woocommerce plugin.
It contains unittests for functions that are independent of WordPress or Woocommerce functionality, focusing on the `php/Blockonomics.php` file as it contains most of the plugin's functionality.
- Pull changes to your local machine
- Navigate to the project directory where the `composer.json` file is located
- Run `composer install` to install the required dependencies. This step requires Composer to be installed on your machine.
- If you don't have Composer installed, you can download it [here](https://getcomposer.org/download/).
- Once the dependencies are installed, you can run the tests using the following command: `vendor/bin/phpunit tests/`
Note: The `vendor` directory is included in the `.gitignore` file and therefore …

Add Initial Unit Tests and Update Composer Dependencies

---

php/Blockonomics.php
php/form_fields.php

The debug log shared by merchant [here](https://wordpress.org/support/topic/latest-update-prevented-admin-login-account-creation/) shows a php warning about "Headers already sent"
`PHP Warning: Cannot modify header information - headers already sent by (output started at /homepages/44/MDSP/htdocs/wordpress/wp-content/plugins/blockonomics-bitcoin-payments/php/form_fields.php:1) in /homepages/44/MDSP/htdocs/wordpress/wp-includes/http.php on line 505
`
This is caused by [empty line before php tag](https://github.com/blockonomics/woocommerce-plugin/blob/4e9fa04a622afadc7767286ad2807598338dcd4f/php/form_fields.php#L1) declaration in `php/form_fields.php` file. This is causing php functions that need to send HTTP headers (like setcookie(), session_start(), or header()) to fail because content …

Fix headers already sent error in version 3.7.4

---

README.md
blockonomics-woocommerce.php
php/Blockonomics.php
templates/blockonomics_nojs_checkout.php

This PR aims to reduce pending issues (currently 27) and push smaller fixes which will be included for version 3.7.7 release.
Commits and issue which they close:
- 8ef6450b76b5328059d55dfcfe2dea459bd9c0be ➡️ https://github.com/blockonomics/woocommerce-plugin/issues/374
No JS checkout now shows amount paid and pending amount
---
- f5e790fd18da6313c958022290dc375db24c5f53 ➡️ https://github.com/blockonomics/woocommerce-plugin/issues/330
- Changed error msg to convey that instructions refer to WP admin dashboard not blockonomics.co and also added missing `</ul>`
---
- aa92ca5b11cec543748f0c81dd9da5b18fe05e21 ➡️ https://github.com/blockonomics/woocommerce-plugin/issues/357
---
- dfc5d6a2e95408b9a2e0d49da987bf2abaa9baa6 ➡️ https://github.com/blockonomics/woocommerce-plugin/issues/329
Adds error …

Multiple small fixes for v3.7.7 release

---

blockonomics-woocommerce.php
composer.lock
php/Blockonomics.php
php/class-blockonomics-setup.php
tests/BlockonomicsTest.php

Recently a bug was reported about deprecated warning on installing the Blockonomics plugin -> Ticket [here](https://blockonomics.freshdesk.com/a/tickets/338040).
**Fix**: Changed the parent slug in `add_submenu_page()` from empty string to `'options.php'` to resolve PHP 8.1 deprecation warnings while maintaining hidden menu functionality ➞ f7784a375b621ce1b84c0de3e1457ea515a68814
- Before this, we were using `null`:
- Using it caused PHP 8.1 deprecation warnings in WordPress core functions
- Specifically triggers warnings in:
- `strpos()`: When WordPress checks menu hierarchy
- `str_replace()`: During menu slug processing
- This occurs because WordPress core functions expect string types but receive null
- Using empty string (`''`) (as the suggested fix by user report): 
- Resolves the …

Php 8.2 Deprecation Warning Fixes

---

blockonomics-woocommerce.php
composer.lock
php/Blockonomics.php
php/class-blockonomics-setup.php
tests/BlockonomicsTest.php

- Removed `/api` suffix from `BASE_URL` and `BCH_BASE_URL` constants
- Standardized API endpoint construction by explicitly adding `/api` prefix where needed
- Fixed transaction URL construction:
- BTC: `https://www.blockonomics.co/#/search?q={txid}&addr={address}`
- BCH: `https://bch.blockonomics.co/api/tx?txid={txid}&addr={address}`
- Updated all store-related API endpoints to use consistent `/api/v2/stores` pattern
- Makes base URL constants more intuitive and less prone to bugs
- Ensures consistent API endpoint construction across the codebase
- Fixes BCH transaction URL format to match expected pattern
- Improves code maintainability by removing duplicate code

Code cleaning for URL construction

---

blockonomics-woocommerce.php
php/Blockonomics.php

Markite theme is showing the Payment Method Discount text on checkout, even when it's set to 0.
I've added a check to apply the [add_fee](https://wp-kama.com/plugin/woocommerce/function/WC_Cart::add_fee) method only when discount > 0

[Fix] 0 discount shown on some themes
